name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: sudo DEBIAN_FRONTEND=noninteractiveapt-get install libncurses5-dev libncursesw5-dev 
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  
  clippy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Check Clippy
        uses: actions-rs/clippy-check@v1.0.0
