name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: sudo DEBIAN_FRONTEND=noninteractive apt-get install libncurses5-dev libncursesw5-dev 
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Cargo Tarpaulin
      run: cargo install cargo-tarpaulin && cargo tarpaulin -o Xml
    - name: Codecov
      uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{secrets.CODECOV_TOKEN}} #required
        file: ./cobertura.xml #optional
        flags: unittests #optional
  
  clippy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Check Clippy
        uses: actions-rs/clippy-check@v1.0.0
